### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by psycholyzern** [TruboXL/wondershaper#2]
Got this error

```
Makefile:2: *** missing separator.  Stop.
```

**Comment by TruboXL** [comment]
Oops... Sorry about that!
I used soft tabs in the Makefile, it will be fixed with hard tabs...

Also please note that this repository is only a hobby for me, so don't really expect I can fix lots of (complex) stuffs >.<

**Comment by TruboXL** [comment]
Fixed!
